### ISSUE TITLE
useEffect and useLayoutEffect

### ISSUE THREAD

**Issue by jchavarri** [jchavarri/jsoo-react#6]
The callbacks need to be wrapped with `caml_js_wrap_callback` (see `useReducer`).

**Comment by benschinn** [comment]
I am trying to regenerate the bundle in `lib` by running `yarn install && yarn bundle`, but I am getting `error Command "bundle" not found.`. I am also not seeing bundle as a CLI command on yarn docs.

**Comment by jchavarri** [comment]
Oh, those steps are not necessary. With the current approach, there's no need to bundle `react` or `react-dom` as they are linked directly in `dune`:

https://github.com/jchavarri/rroo/blob/528a9d5c26454a74d25c698c9f33b5b5a6994f59/lib/dune#L5-L6

I removed the `readme` file in `lib` as I think the main instructions should suffice. Let me know if anything else is unclear or if you run into any issues! :)

**Comment by benschinn** [comment]
Just want to make sure I understand what needs to happen for this issue:
1. Write binding in to useEffect and useLayoutEffect functions in `lib/React.re`
2. Write wrappers in `lib/React.js`?
3. Write stubs in `lib/React.c`?

I don't totally understand what is going on in `React.js`. Why are we writing some functions in this file, when we have bindings written to react?

**Comment by jchavarri** [comment]
Yes 👍 I just updated `interop.md` with more information and a section for this in particular: https://github.com/jchavarri/rroo/blob/master/interop.md#adding-a-new-binding-to-a-react-function

> So the bindings are not to the react module directly, but to lib/React.js.

Exactly, the bindings need to point to a "native file" (in Js_of_ocaml a `.js` file) that backs the module and defines the external functions.

> Are there other steps that I am unaware of?

It would be awesome to add a new component `UseEffect` that includes usages of both functions 🙂
